### ISSUE TITLE
Cannot drag the Typora window

### ISSUE THREAD

**Issue by ghost** [TEParsons/Krafty#1]
cannot drag the Typora window when using the "Krafty" theme

**Comment by TEParsons** [comment]
The actual window itself? Typora themes are just a CSS stylesheet, so it's strange that it should affect the window... What happens when you try to drag it? Does it just not respond, or do bits stay in place?

**Comment by ghost** [comment]
When I change the Typora theme from _Github_ or others to _Krafty_, the window becomes stationary. So I couldn't drag it as much as I wanted.

**Comment by TEParsons** [comment]
Does the window then become moveable again when you switch back to *Github*?

**Comment by ghost** [comment]
Yes, it does.

**Comment by TEParsons** [comment]
What operating system and version of Typora are you using? I'll need to recreate this error before I can fix it - and I can move the window around with no trouble on my (Windows 10, Typora 1.1.5) setup

**Comment by ghost** [comment]
Typora 1.1.5 for Windows 10, too.
And here is a GIF to show the phenomenon.
![GIF 2022-3-12 13-15-11](https://user-images.githubusercontent.com/45620695/158004900-3899e4af-e60d-4f1d-a104-e93df145ac29.gif)

**Comment by TEParsons** [comment]
Ah I see, you've got appearance set to unibody - that's why I couldn't recreate the error, I have mine in Classic. If I set mine to unibody it does that too, so now I can replicate the error I can figure out what's causing it

**Comment by ghost** [comment]
Nice! Thanks for your time.

**Comment by TEParsons** [comment]
Found the bug! Essentially, to make the background stick in place, I set its position to `fixed` and its top position to `0` - in Unibody mode, the window bar is actually a part of the HTML of the page, so when I set `top` to 0 it positions the background over the hitbox for the window bar. 

I'll actually raise this as an issue on the Typora GitHub too, as I bet there's a way to ensure that the context of the `content` object is fully independent of the window itself, to avoid novices like me accidentally breaking the window :P
